import discord
import asyncio
from discord import Game
from discord.ext.commands import Bot
import datetime
import os

client = discord.Client()

@client.event
async def on_ready():
    print('Logged in')
    print('Name : {}'.format(client.user.name))
    print('ID : {}'.format(client.user.id))
    print(discord.__version__)

@client.event
async def on_message(message):
	user = message.author
	if message.content == '!HorseNoti1':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		role = discord.utils.find(lambda r: r.name == "HorseNoti1", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered horse\'s notification type 1'.format(message.author.mention))
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "HorseNoti2", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "HorseNoti3", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content == '!HorseNoti2':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		role = discord.utils.find(lambda r: r.name == "HorseNoti2", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered horse\'s notification type 2'.format(message.author.mention))
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "HorseNoti1", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "HorseNoti3", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content == '!HorseNoti3':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		role = discord.utils.find(lambda r: r.name == "HorseNoti3", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered horse\'s notification type 3'.format(message.author.mention))
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "HorseNoti1", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "HorseNoti2", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content == '!MarketNoti':
		await client.add_reaction(message, "👌")
		role = discord.utils.find(lambda r: r.name == "MarketNoti", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered market\'s notification'.format(message.author.mention))
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content == '!imok':
		await client.add_reaction(message, "👌")
		role = discord.utils.find(lambda r: r.name == "DarkHorse", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered Horse Market'.format(message.author.mention))
		await asyncio.sleep(10)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content == '!HorseNotiDel':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		msg = await client.send_message(message.channel, '{} We removed your all horse\'s notification '.format(message.author.mention))
		role = discord.utils.find(lambda r: r.name == "HorseNoti1", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "HorseNoti2", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "HorseNoti3", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content == '!MarketNotiDel':
		await client.add_reaction(message, "👌")
		role = discord.utils.find(lambda r: r.name == "MarketNoti", message.server.roles)
		await client.remove_roles(user, role)
		msg = await client.send_message(message.channel, '{} We removed your market\'s notification '.format(message.author.mention))
		await asyncio.sleep(10)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content.upper() == '!ALLTIER':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		role = discord.utils.find(lambda r: r.name == "AllTier", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered horse\'s notification All Tier'.format(message.author.mention))
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T1", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T2", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T3", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T4", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T5", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T6", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T7", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T8", message.server.roles)
		await client.remove_roles(user, role)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content.upper() == '!T1':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		role = discord.utils.find(lambda r: r.name == "T1", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered horse\'s notification T1'.format(message.author.mention))
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "AllTier", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content.upper() == '!T2':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		role = discord.utils.find(lambda r: r.name == "T2", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered horse\'s notification T2'.format(message.author.mention))
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "AllTier", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content.upper() == '!T3':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		role = discord.utils.find(lambda r: r.name == "T3", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered horse\'s notification T3'.format(message.author.mention))
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "AllTier", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content.upper() == '!T4':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		role = discord.utils.find(lambda r: r.name == "T4", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered horse\'s notification T4'.format(message.author.mention))
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "AllTier", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content.upper() == '!T5':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		role = discord.utils.find(lambda r: r.name == "T5", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered horse\'s notification T5'.format(message.author.mention))
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "AllTier", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content.upper() == '!T6':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		role = discord.utils.find(lambda r: r.name == "T6", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered horse\'s notification T6'.format(message.author.mention))
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "AllTier", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content.upper() == '!T7':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		role = discord.utils.find(lambda r: r.name == "T7", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered horse\'s notification T7'.format(message.author.mention))
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "AllTier", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content.upper() == '!T8':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		role = discord.utils.find(lambda r: r.name == "T8", message.server.roles)
		await client.add_roles(user, role)
		msg = await client.send_message(message.channel, '{} registered horse\'s notification T8'.format(message.author.mention))
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "AllTier", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	elif message.content.upper() == '!ALLTIERDEL':
		await client.add_reaction(message, "👌")
		await client.send_message(discord.Object(id='455792184294113300'), datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S') +'->('+ str(message.author) +')->\" '+message.content+' \"')
		msg = await client.send_message(message.channel, '{} We removed your all Tier horse\'s notification '.format(message.author.mention))
		role = discord.utils.find(lambda r: r.name == "AllTier", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T1", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T2", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T3", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T4", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T5", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T6", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T7", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		role = discord.utils.find(lambda r: r.name == "T8", message.server.roles)
		await client.remove_roles(user, role)
		await asyncio.sleep(1)
		await client.delete_message(message)
		await client.delete_message(msg)
	


client.run(os.getenv('TOKEN'))
